server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name abkasmi.42.fr;

    ssl on;
    ssl_protocols TLSv1.3;
    ssl_certificate /etc/nginx/ssl/abkasmi.42.fr.crt;
    ssl_certificate_key /etc/nginx/ssl/abkasmi.42.fr.key;
    
    add_header Strict-Transport-Security "max-age=0;";

    index index.php;
    root /var/www/wordpress;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
    }
}
