server {
    server_name	abkasmi.42.fr;

	listen 443 ssl;
	listen [::]:443 ssl;
	
    root /var/www/wordpress;
	index index.php;

	autoindex on;

	ssl	on;
	ssl_certificate		/etc/nginx/ssl/abkasmi.42.fr.crt;
	ssl_certificate_key	/etc/nginx/ssl/abkasmi.42.fr.key;
	ssl_protocols		TLSv1.3;

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass 172.23.0.1:9000;
		include /etc/nginx/conf.d/*.conf;
		include /etc/nginx/sites-enabled/*;
	}
}
